[package]
name = "groups"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
rand = "0.8"
smallvec = "1.13"

[dev-dependencies]
proptest = "1.4"
criterion = { version = "0.5", default-features = false }

[[bench]]
name = "permutation_op"
harness = false

[[bench]]
name = "wreath_op"
harness = false

[[bench]]
name = "schreier_sims_construction"
harness = false

[[bench]]
name = "bsgs_sift"
harness = false
