//! Deterministic Schreier–Sims (Sims 1970).
//!
//! Builds a Base + Strong Generating Set (BSGS) by exhaustively sifting
//! Schreier generators. Provably correct.
//!
//! ## Algorithm sketch
//!
//! Given a generating set `S` and a (possibly partial) base `B`:
//!
//! 1. Initialize the chain as a sequence of stabilizer levels, one per base
//!    point. Level `i`'s strong generators are those of `S` fixing
//!    `b_1, …, b_{i-1}`.
//! 2. For each level (top-down), build the orbit of `b_i` under the level's
//!    strong generators, with a transversal (full coset rep table).
//! 3. Generate Schreier generators `s · u_β · u_{β·s}^{-1}` for each
//!    transversal point `β` and each generator `s`. Sift each through deeper
//!    levels. If the residue is non-trivial, add it to that deeper level's
//!    strong generators and re-extend the orbit. Loop until all Schreier
//!    generators sift to identity.
//! 4. Extend the base lazily when a Schreier residue fixes all current base
//!    points (it must move some point — choose one and append).

use smallvec::SmallVec;

use crate::bsgs::{Bsgs, PermutationLike, StabilizerLevel};
use crate::generators::GeneratingSet;

/// Build a BSGS from `gens` using the given base hint. The base is extended
/// automatically if it isn't faithful.
pub fn deterministic<G, const N: usize>(
    gens: &GeneratingSet<G>,
    base_hint: &[u16],
) -> Bsgs<G, N>
where
    G: PermutationLike<N>,
{
    let mut bsgs: Bsgs<G, N> = Bsgs::empty();
    bsgs.base = SmallVec::from_iter(base_hint.iter().copied());

    // Seed the chain with one level per hinted base point. All gens sit at
    // level 0; deeper levels start with no strong gens until we discover
    // Schreier residues.
    for &b in base_hint {
        bsgs.levels.push(StabilizerLevel::empty(b));
    }
    if bsgs.levels.is_empty() {
        // No base supplied. Synthesize one starting from a point moved by
        // some generator.
        if let Some(b) = first_moved_point::<G, N>(gens) {
            bsgs.base.push(b);
            bsgs.levels.push(StabilizerLevel::empty(b));
        } else {
            // The group is trivial.
            return bsgs;
        }
    }

    // Top-level strong gens are everything in the user's set.
    bsgs.levels[0].strong_gens = gens.iter().map(|(_, g)| *g).collect();

    sift_schreier_generators(&mut bsgs);
    bsgs
}

/// Find the first point moved by some generator, or `None` if all generators
/// are the identity.
fn first_moved_point<G, const N: usize>(gens: &GeneratingSet<G>) -> Option<u16>
where
    G: PermutationLike<N>,
{
    for (_, g) in gens.iter() {
        for i in 0..(N as u16) {
            if g.apply_to(i) != i {
                return Some(i);
            }
        }
    }
    None
}

/// Repeatedly extend orbits and sift Schreier generators until the chain is
/// closed (every Schreier generator at every level sifts to identity).
fn sift_schreier_generators<G, const N: usize>(bsgs: &mut Bsgs<G, N>)
where
    G: PermutationLike<N>,
{
    // Build orbits and transversals for all current levels first.
    for i in 0..bsgs.levels.len() {
        extend_orbit(bsgs, i);
    }

    let mut changed = true;
    while changed {
        changed = false;
        // Walk levels top-down; for each, generate Schreier generators and
        // sift them through deeper levels.
        for i in 0..bsgs.levels.len() {
            // S_i is generated by the union of strong gens from levels [i, end].
            let mut level_strong_gens: Vec<G> = Vec::new();
            for lvl in &bsgs.levels[i..] {
                level_strong_gens.extend(lvl.strong_gens.iter().copied());
            }
            let level_transversal = bsgs.levels[i].transversal.clone();

            // Iterate every (β in orbit of b_i) × (strong generator s).
            for (beta, u_beta_opt) in level_transversal.iter().enumerate() {
                let Some(u_beta) = u_beta_opt else { continue };
                for s in &level_strong_gens {
                    // Schreier generator: u_β · s · u_{β·s}⁻¹
                    let beta_s = s.apply_to(beta as u16);
                    let Some(u_beta_s) = bsgs.levels[i].transversal[beta_s as usize] else {
                        // β·s not yet in the orbit — extend_orbit should have
                        // covered this. Defensive: re-extend and continue.
                        extend_orbit(bsgs, i);
                        continue;
                    };
                    let schreier = u_beta.op(s).op(&u_beta_s.inv());

                    // Sift through deeper levels.
                    let mut residue = schreier;
                    let mut sifted_to_level: Option<usize> = None;
                    for j in (i + 1)..bsgs.levels.len() {
                        let img = residue.apply_to(bsgs.levels[j].base_point);
                        match bsgs.levels[j].transversal[img as usize] {
                            Some(u) => residue = residue.op(&u.inv()),
                            None => {
                                sifted_to_level = Some(j);
                                break;
                            }
                        }
                    }

                    if residue == G::identity() {
                        continue; // sifted clean
                    }

                    // Non-identity residue: add it as a strong gen at the
                    // appropriate level and possibly extend the base.
                    let target_level = match sifted_to_level {
                        Some(j) => j,
                        None => {
                            // Sifted through all levels but residue ≠ identity.
                            // Need to extend the base with a point this residue
                            // moves.
                            let new_base = (0..N as u16)
                                .find(|&p| residue.apply_to(p) != p)
                                .expect("non-identity element fixes all points?");
                            bsgs.base.push(new_base);
                            bsgs.levels.push(StabilizerLevel::empty(new_base));
                            bsgs.levels.len() - 1
                        }
                    };
                    bsgs.levels[target_level].strong_gens.push(residue);
                    extend_orbit(bsgs, target_level);
                    changed = true;
                }
            }
        }
    }
}

/// Compute the orbit of `bsgs.levels[i].base_point` under the union of strong
/// generators from levels `[i, end]`.
///
/// Crucial subtlety: a strong generator stored at level `j ≥ i` lives in `S_i
/// ⊃ S_j` and so is a generator of `S_i` for orbit-construction purposes.
/// Using only `levels[i].strong_gens` would underestimate the orbit.
fn extend_orbit<G, const N: usize>(bsgs: &mut Bsgs<G, N>, level: usize)
where
    G: PermutationLike<N>,
{
    let base_point = bsgs.levels[level].base_point;
    // Reset the transversal — orbit may have grown.
    let mut transversal: Vec<Option<G>> = (0..N).map(|_| None).collect();
    transversal[base_point as usize] = Some(G::identity());

    // Union strong gens from this level and all deeper levels.
    let mut strong_gens: Vec<G> = Vec::new();
    for lvl in &bsgs.levels[level..] {
        strong_gens.extend(lvl.strong_gens.iter().copied());
    }

    let mut frontier: Vec<u16> = vec![base_point];
    while let Some(beta) = frontier.pop() {
        let u_beta = transversal[beta as usize].expect("frontier point must have a rep");
        for s in &strong_gens {
            let img = s.apply_to(beta);
            if transversal[img as usize].is_none() {
                transversal[img as usize] = Some(u_beta.op(s));
                frontier.push(img);
            }
        }
    }
    bsgs.levels[level].transversal = transversal.into_boxed_slice();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::permutation::Permutation;

    #[test]
    fn s_n_via_adjacent_transpositions() {
        // S_4 generated by (0 1), (1 2), (2 3) — known to be S_4 of order 24.
        let gens = GeneratingSet::with_inverses([
            Permutation::<4>::transposition(0, 1),
            Permutation::<4>::transposition(1, 2),
            Permutation::<4>::transposition(2, 3),
        ]);
        let bsgs = deterministic::<_, 4>(&gens, &[0, 1, 2]);
        assert_eq!(bsgs.order(), 24);
    }

    #[test]
    fn s_5_via_adjacent_transpositions() {
        let gens = GeneratingSet::with_inverses([
            Permutation::<5>::transposition(0, 1),
            Permutation::<5>::transposition(1, 2),
            Permutation::<5>::transposition(2, 3),
            Permutation::<5>::transposition(3, 4),
        ]);
        let bsgs = deterministic::<_, 5>(&gens, &[0, 1, 2, 3]);
        assert_eq!(bsgs.order(), 120);
    }

    #[test]
    fn s_5_via_two_generators() {
        // S_n is generated by (0 1) and the n-cycle (0 1 ... n-1).
        let gens = GeneratingSet::with_inverses([
            Permutation::<5>::transposition(0, 1),
            Permutation::<5>::cycle(&[0, 1, 2, 3, 4]),
        ]);
        let bsgs = deterministic::<_, 5>(&gens, &[0, 1, 2, 3]);
        assert_eq!(bsgs.order(), 120);
    }

    #[test]
    fn membership_in_s_4() {
        let gens = GeneratingSet::with_inverses([
            Permutation::<4>::transposition(0, 1),
            Permutation::<4>::transposition(1, 2),
            Permutation::<4>::transposition(2, 3),
        ]);
        let bsgs = deterministic::<_, 4>(&gens, &[0, 1, 2]);
        // Every element of S_4 is in the group.
        for p in <Permutation<4> as crate::Enumerable>::iter() {
            assert!(bsgs.is_member(&p), "{p} should be in S_4");
        }
    }

    #[test]
    fn alternating_group_membership() {
        // A_4 is generated by 3-cycles. Use (0 1 2) and (1 2 3).
        let gens = GeneratingSet::with_inverses([
            Permutation::<4>::cycle(&[0, 1, 2]),
            Permutation::<4>::cycle(&[1, 2, 3]),
        ]);
        let bsgs = deterministic::<_, 4>(&gens, &[0, 1, 2]);
        // |A_4| = 12
        assert_eq!(bsgs.order(), 12);

        // Even permutations are members; odd are not.
        for p in <Permutation<4> as crate::Enumerable>::iter() {
            let expected = p.parity() == 0;
            assert_eq!(
                bsgs.is_member(&p),
                expected,
                "parity={} membership mismatch for {p}",
                p.parity()
            );
        }
    }

    #[test]
    fn cyclic_group_in_s_4() {
        // A 4-cycle generates a cyclic subgroup of order 4.
        let gens = GeneratingSet::with_inverses([Permutation::<4>::cycle(&[0, 1, 2, 3])]);
        let bsgs = deterministic::<_, 4>(&gens, &[0]);
        assert_eq!(bsgs.order(), 4);
    }

    #[test]
    fn empty_base_extends_automatically() {
        let gens = GeneratingSet::with_inverses([Permutation::<4>::cycle(&[0, 1, 2, 3])]);
        let bsgs = deterministic::<_, 4>(&gens, &[]);
        assert_eq!(bsgs.order(), 4);
    }

    #[test]
    fn word_for_short_targets() {
        let gens = GeneratingSet::with_inverses([
            Permutation::<4>::transposition(0, 1),
            Permutation::<4>::transposition(1, 2),
            Permutation::<4>::transposition(2, 3),
        ]);
        let bsgs = deterministic::<_, 4>(&gens, &[0, 1, 2]);
        let target = Permutation::<4>::cycle(&[0, 1, 2]);
        let w = bsgs.word_for(&gens, &target).expect("should be in S_4");
        assert_eq!(w.evaluate(&gens), target);
    }
}
